---
version: '3'
services:
  rks-consul:
    image: "consul:1.6.1"
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - demo
  rks-vault:
    image: "vault:1.3.1"
    cap_add:
      - IPC_LOCK
    command: vault server -config=/etc/vault/vault_server.hcl -log-level=debug
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    volumes:
      - ./scripts/vault_server.hcl:/etc/vault/vault_server.hcl
    networks:
      - demo
  rks-server:
    build:
      context: .
    command: --vaultaddr http://rks-vault:8200 --adminLogin admin-rks --adminPwd 12345
    ports:
      - "8080:8080"
    networks:
      - demo

networks:
  demo:
