name: Remote Key Server CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: [ubuntu-latest]
    container: golangci/golangci-lint:v1.24.0
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: go get ./...
      - name: Run linter
        run: golangci-lint run ./...

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: make -j $(nproc) test
